name: data_cache_x
description: "A Flutter package for efficient offline data caching and synchronization with enhanced security features and tag-based cache management."
version: 0.2.0

homepage: https://github.com/Liv-Coder
repository: https://github.com/Liv-Coder/data_cache_x

environment:
  sdk: ^3.2.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  get_it: ^8.0.3
  # workmanager dependency removed due to compatibility issues with newer Flutter versions
  logging: ^1.3.0
  sqflite: ^2.4.2
  shared_preferences: ^2.5.3
  path: ^1.9.1
  encrypt: ^5.0.3
  archive: ^4.0.7
  flutter_secure_storage: ^9.2.4
  crypto: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  hive_generator: ^2.0.1
